### group_name
group: VIT_MAE_PRETRAINING_small_set_one_channel

### dataset ###
dataset:
  train: datasets/ZooScan77_small/train
  val: datasets/ZooScan77_small/val


### hyperparams

transforms:
  normalize:
    mean: 0.9044
    std:  0.1485

eval_every_x_steps: 300

num_epochs: 15

learning_rate_range:
  min: 1e-6
  max: 1e-2

optimizers:
  - AdamW

momentum: # momentum in sgd or beta l in adam(W)
  min: 0.8
  max: 0.99

beta2: # in adam(W)
  min: 0.98
  max: 1.0

batch_size_range: # [4, 8, ... 128]
  min: 4
  max: 128

weight_decay:
  min: 1e-6
  max: 1e-1

warmup_fraction:
  min: 1e-4
  max: 0.1

warmup_epochs:
  min: 0.0
  max: 5.0

storage: sqlite:///pretraining/optimize/storage/optuna_study_small_one_channel.db
wandb_project: optuna_small_set_one_channel

