num_classes: 77
num_workers: 1

batch_size: 64
max_num_epochs: 50

model:
  name: vit #vit # deit
  pretrained: true
  fine_tune: true  # If true, fine-tune the entire model; if false, freeze earlier layers
  freeze_until: none  # Options could be "all", "none", or specific layer like "layer4"

optimizer:
  type: "Adam"  # or "SGD"
  lr: 0.00005

scheduler:
  enable: false
  type: "CosineAnnealingLR"
  T_max: 50  # Number of epochs before first restart
  eta_min: 0.000001  # Minimum lr

early_stopping:
  early_stopping_metric: balanced_accuracy # loss, accuracy or balanced_accuracy
  patience: 5

reports:
  enable: true
  frequency: 1

checkpoint: true # save model and training parameters

dataset: ZooScan77_small